### ISSUE TITLE
Find elements from a parent element

### ISSUE THREAD

**Issue by mike123vn** [Xotabu4/protractor-element-extend#12] opened 2017-04-24 16:41 UTC
I tried 3 ways to Find elements from a parent element but none of them work.

```
class ComboboxClass extends BaseFragment {
    constructor(element) {
        super(element) 
    }

    selectDropdownByIndex(index, milliseconds) {
        this.findElements(by.tagName('option'))//Error in run time cannot find method findElements
            .then(function (options) {
                options[index].click();
            });
        if (typeof milliseconds !== 'undefined') {
            browser.sleep(milliseconds);
        }
    }

    selectRandom() {
        this.element.all(by.xpath('//option')) //Webstorm hightlight .all
            .then(function (options) {
                let random = Math.floor((Math.random() * (options.length - 1)));
                if (options.length > 0) {
                    options[random].click();
                }
            });


    }
}
selectDropdownByText(Text, milliseconds) {
        this.$$('option'))//Invalid locator
            .then(function (options) {
                for (let i = 0; i < options.length; i++) {
                    if (options[i].getText()
                            .then(function (textGet) {
                                if (textGet == Text) {
                                    return true;
                                }
                                else {
                                    return false;
                                }
                            })) {

                        options[i].click();
                    }

                }
            });
        if (typeof milliseconds !== 'undefined') {
            browser.sleep(milliseconds);
        }
    }
```

**Comment by Xotabu4** [comment] 2017-04-24 16:46
@mike123vn Thanks! You should threat 'this' as a ElementFinder. Try to search with 'this.element(by.css("option"))...
ElementFinder does not has .findElement methods, and this.$/this.$$ shortcuts are with nasty bug, that i now trying to fix now.

**Comment by Xotabu4** [comment] 2017-04-25 12:12
@mike123vn also try 
`this.all(by.css(...))` to search for all elements.

I would suggest to try to migrate to TypeScript to add autocomplete into your protractor code.

**Comment by mike123vn** [comment] 2017-04-25 14:10
Hi Xotabu4,

I tried. But it seems to be that it will find al of element including options from other combo boxes in page. It's not what i'm looking for. If i want to use it, i don't need to specific a combo box :)

**Comment by Xotabu4** [comment] 2017-04-25 14:22
@mike123vn Not quite sure whats the question is. 
If you want to search inside element - make calls to 'this' object, like 'this.element(by.xpath(...))'

If you want to search everywhere on the page - you can still call global browser object in your fragments:
`element(by.xpath(...))` or whatever locator works for you.

It is possible that your Options elements are actually not nested elements of 'this' - it happens often in modern markup. In this case searching inside `this` can return 0 results

**Comment by mike123vn** [comment] 2017-04-25 14:29
Hi Xotabu,

i tried this.all(by.xpath(//option)) but the result i got is not only the option tag of a combo box but also all the option tag in Dom.

**Comment by Xotabu4** [comment] 2017-04-25 14:31
@mike123vn
Can you also share piece of HTML that you are working with?

**Comment by mike123vn** [comment] 2017-04-25 14:41
Sure. Kindly check it

**Comment by Xotabu4** [comment] 2017-04-25 15:13
@mike123vn sorry, website that you sent - is broken in this .zip

Just go thru your DOM structure, make sure that you correctly looking for element that you are trying to use. This lib does not change search behavior. When you use it it is totally same as using `$('selector').$('option')` or `element(by.css('selector')).element(by.css('option'))`

**Comment by mike123vn** [comment] 2017-04-25 15:41
actually it work when i try to find 1 element in combo box like this.element(by.xpath('.//option')), but when using this.all(by.xpath('.//option'), it tried to catch all option tag in Dom.

**Comment by Xotabu4** [comment] 2017-04-25 15:45
@mike123vn Can you share the error that you get when doing `this.all(by.xpath('.//option'))` ?

**Comment by mike123vn** [comment] 2017-04-25 15:56
Actually i don't get any error but it give me the result of all the element having tag options in DOM. For example, i have 3 combo box, my first combo box just have 2 option. But using  .all i get a array of 10.

**Comment by Xotabu4** [comment] 2017-04-26 11:59
@mike123vn 
I wasn't able to see what page you are trying to test, and what element you are passing into constructor function.

You should verify again your element that you are passing into BaseFragment constructor function. Nested search will be done inside it. I rechecked this - logic is same as in protractor code. If your element inside has 10 options (visible or not) you will get them all.

Thanks!

**Comment by mike123vn** [comment] 2017-04-27 11:55
Hi,
I just check again
comboBox(productLine).selectRandom();
with selectRamdom using this module
[18:49:02] E/launcher - Error: BUG: elementArrayFinder cannot be empty
[18:49:02] E/launcher - Error: Error: BUG: elementArrayFinder cannot be empty

```
>     selectRandom() {
>         this.click();
>         this.all(by.css('option'))
>             .then(function (options) {
>                 let random = Math.floor((Math.random() * (options.length - 1)));
>                 console.log(random);
>                 if (options.length > 0) {
>                     options[random].click();
>                     browser.sleep(2000);
>                 }
>             });
> 
> 
>     }
```

> export function comboBox(locator, elementFlag = true) {
>     if (elementFlag != false) {
>         return new ComboboxClass(locator);
>     }
>     else {
>         return new ComboboxClass(element(locator));
>     }
> 
> 
> }

```

```

However, with selectRandom is a function in my helper class. It work well
          helper.selectRandom(element(productLine));

```
   public selectRandom(ele) {
        ele.click();
        ele.$$('option')
        .then(function (options) {
            let random = Math.floor((Math.random() * (options.length - 1)));
            console.log(random);
            if (options.length > 0) {
                options[random].click();
                browser.sleep(2000);
            }
        });


    }
```

**Comment by Xotabu4** [comment] 2017-04-27 12:13
@mike123vn 
[18:49:02] E/launcher - Error: BUG: elementArrayFinder cannot be empty
[18:49:02] E/launcher - Error: Error: BUG: elementArrayFinder cannot be empty

This error from ProtractorJS when you are trying to create ElementFinder object but do not pass ElementArrayFinder object into constructor function.

Find usage of your `export function comboBox(locator, elementFlag = true)`
and check that you are passing correct type of object into it. 

`new ComboboxClass(locator)` locator here must be instance of ElementFinder.

**Comment by mike123vn** [comment] 2017-04-27 13:39
helper.selectRandom(element(productLine));
comboBox(productLine).selectRandom();
You can see productLine is a locator, not a web element. I just put two sentences near by and comment one of them to check the result. If I put the wrong type, I will get error: invalid locator

**Comment by Xotabu4** [comment] 2017-04-27 14:38
@mike123vn 
```typescript
export function comboBox(locator, elementFlag = true) {
if (elementFlag != false) {
return new ComboboxClass(locator);
}
else {
return new ComboboxClass(element(locator));
}

}
```

`elementFlag = true` parameter is true by default, you are passing `productLine` which is Locator object i think. So `if (elementFlag != false) {` will drop you into `return new ComboboxClass(locator);` so you are passing Locator object into BaseFragment constructor - and there it goes to ElementFinder constructor, where it trying to find attribute `elementArrayFinder` on your Locator object that is obviously not exist in this object.


I would suggest to remove this `function comboBox` totally, and just export ComboboxClass from file. 

Also you can try to handle this on constructor level:

```typescript
class ComboboxClass2 extends BaseFragment {
    constructor(extendable: ElementFinder | Locator) {
        if (extendable instanceof ElementFinder) {
            super(extendable)
        } else {
            super(element(extendable))
        }
        
    }
}
```

**Comment by mike123vn** [comment] 2017-04-27 16:20
I'm really sorry because of my mistake. I'm so careless.
However, as i said two days ago, element.all just finds all the elements having tag option in DOM not producing any error.   
`public cbo_ProductLine: Locator = by.id("d_productLine");`

            it('#7 plus Get all option of Product Line', async function () {
                //put data to inspection information

                BookAnInspection.selectSlideMenu("Detail Of PI/PO");
                comboBox(BookAnInspection.cbo_ProductLine,false).getOptions();

            })

 ```


   getOptions() {

        this.all(by.xpath('//option'))
            .then(function (options) {
                for (let i = 0; i < options.length; i++) {
                    options[i].getText()
                        .then(function (textGet) {
                            console.log(textGet);
                        })
                }


            })

    }

```

```
export function comboBox(locator, elementFlag = true) {
    if (elementFlag != false) {
        return new ComboboxClass(locator);
    }
    else {
        return new ComboboxClass(element(locator));
    }


}
```
This is the log i get when i try to get the options of a combo box

```
Footwear
Garments and Apparel
Furniture
Frozen Food
Electronics
Cooling & Heating
Baby Gear
Afghanistan
Åland Islands
Albania
Algeria
...

```

**Comment by Xotabu4** [comment] 2017-04-28 11:28
@mike123vn 
Hi mike! I looked closely on your issue. And you are actually right! 

Check this:
https://github.com/Xotabu4/Protractor-Experiments/blob/master/experiments/pagefragments/verifybug.ts#L159

using chaining with css selector - finds only what it should.

And now check next test:
https://github.com/Xotabu4/Protractor-Experiments/blob/master/experiments/pagefragments/verifybug.ts#L170

Using `by.xpath('//options')` finds options elements everywhere on the page ignoring parent element that we are specified as a starting point to search

But using `by.xpath('options')` works as expected.


I would suggest to rewrite your method to not use `//` in nested xpath selectors, since in xpath this means global search. But actually you can report this as a bug to protractor repo - just provide minimal reproducible example.

Something like this.
```typescript
getOptions() {
    return this.all(by.css('option')).getText()
}
```

**Comment by mike123vn** [comment] 2017-04-28 11:43
I got it. Thank you for your great support. I really appreciate it 👍

**Comment by mike123vn** [comment] 2017-04-29 02:51
Hi,
Could you please let me ask another question not related to your great module but related to the method instanceof you mentioned.
I had tried it before but no success. That's why i must use the flag to manual handle checking element of locator. My node version is 6.9.1
When I run as normal, the output is always false.
However, when running in Webstorm debug mode step by step the output of Check ElementFinder is true.

      var listText = element.all((by.xpath("//input[@type='text']"))).filter(function (elm) {
            return elm.isDisplayed().then(function (isDisplayed) {
                return isDisplayed;
            });
        }).then(function(listText){
            for (let i = 0; i < listText.length; i++) {
                console.log("Check ElementFinder"+i+":"+(listText[i] instanceof  ElementFinder));
                console.log("Check web"+i+":"+(listText[i] instanceof  WebElement));
                textBox(listText[i]).setContent("Automation"+i);
                browser.sleep(1000);
            }
        });


Output when running at normal (Type protractor in command line)

```
Check ElementFinder0:false
Check WebElement0:false
Check ElementFinder1:false
Check WebElement1:false
Check ElementFinder2:false
Check WebElement2:false
Check ElementFinder3:false
Check WebElement3:false
Check ElementFinder4:false
Check WebElement4:false
Check ElementFinder5:false
Check WebElement5:false
Check ElementFinder6:false
Check WebElement6:false
Check ElementFinder7:false
Check WebElement7:false
Check ElementFinder8:false
Check WebElement8:false
Check ElementFinder9:false
Check WebElement9:false
Check ElementFinder10:false
Check WebElement10:false
Check ElementFinder11:false
Check WebElement11:false
Check ElementFinder12:false
Check WebElement12:false
Check ElementFinder13:false
Check WebElement13:false
Check ElementFinder14:false
Check WebElement14:false

```
Output running with Webstorm debug 


```
Check ElementFinder0:true
Check WebElement0:false
Check ElementFinder1:true
Check WebElement1:false
Check ElementFinder2:true
Check WebElement2:false
Check ElementFinder3:true
Check WebElement3:false
Check ElementFinder4:true
Check WebElement4:false
Check ElementFinder5:true
Check WebElement5:false
Check ElementFinder6:true
Check WebElement6:false
Check ElementFinder7:true
Check WebElement7:false
Check ElementFinder8:true
Check WebElement8:false
Check ElementFinder9:true
Check WebElement9:false
Check ElementFinder10:true
Check WebElement10:false
Check ElementFinder11:true
Check WebElement11:false
Check ElementFinder12:true
Check WebElement12:false
Check ElementFinder13:true
Check WebElement13:false
Check ElementFinder14:true
Check WebElement14:false
```

**Comment by mike123vn** [comment] 2017-04-29 03:41
I just do very very basic thing but the result is also false:
        console.log("Check locator element "+ (element(this.txt_LoginUsername) instanceof ElementFinder)  );

> Check locator element false

**Comment by Xotabu4** [comment] 2017-04-29 08:20
@mike123vn 
I can answer, but lets go to gitter chat - https://gitter.im/protractor-element-extend/

Docs about this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof
And when you using .then() - https://github.com/angular/protractor/blob/5.1.0/lib/element.ts#L555

I am closing this ticket

**Closed as completed by Xotabu4** 2017-04-29 08:20 UTC
Labels: bug, help wanted
